using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ProjectGranjaLaFlor.Models.ViewModels
{
    /*
     * Represents the editable Daily Check information
     * used by the Create and Edit forms.
     *
     * Calculated database properties are not editable because
     * their values are generated by the DailyCheckService.
     */
    public class DailyCheckFormViewModel
    {
        /*
         * Used during Edit to identify the record.
         * During Create, the value remains zero.
         */
        [Display(Name = "ID")]
        public int DailyCheckId { get; set; }

        /*
         * User-entered and selected values.
         */
        [Required(ErrorMessage = "La fecha es obligatoria.")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha")]
        public DateTime DailyCheckDate { get; set; } = DateTime.Today;

        [Required(ErrorMessage = "Debe seleccionar una pollera.")]
        [Range(
            1,
            int.MaxValue,
            ErrorMessage =
                "Debe seleccionar una pollera válida.")]
        [Display(Name = "Pollera")]
        public int BroilerHouseId { get; set; }

        [Required(ErrorMessage = "Debe seleccionar una camada.")]
        [Range(
            1,
            int.MaxValue,
            ErrorMessage =
                "Debe seleccionar una camada válida.")]
        [Display(Name = "Camada")]
        public int BroodId { get; set; }

        [Required(ErrorMessage = "Debe seleccionar un día de control.")]
        [Display(Name = "Día")]
        public string DailyCheckDay { get; set; } = string.Empty;

        [Required(ErrorMessage = "Debe seleccionar una semana de control.")]
        [Display(Name = "Semana")]
        public string DailyCheckWeek { get; set; } = string.Empty;

        [Required(ErrorMessage = "La mortalidad natural es obligatoria.")]
        [Range(
            0,
            int.MaxValue,
            ErrorMessage =
                "La mortalidad natural no puede ser negativa.")]
        [Display(Name = "Mortalidad natural")]
        public int NaturalMortality { get; set; }

        [Required(ErrorMessage = "La cantidad seleccionada es obligatoria.")]
        [Range(
            0,
            int.MaxValue,
            ErrorMessage =
                "La cantidad seleccionada no puede ser negativa.")]
        [Display(Name = "Selección")]
        public int SelectQuantity { get; set; }

        [Required(ErrorMessage = "El consumo en quintales es obligatorio.")]
        [Range(
            typeof(decimal),
            "0",
            "99999999.99",
            ErrorMessage =
                "El consumo en quintales no puede ser negativo.")]
        [Display(Name = "Consumo en quintales")]
        public decimal ConsumptionQuintals { get; set; }

        [StringLength(
            200,
            ErrorMessage =
                "La descripción no puede superar los 200 caracteres.")]
        [Display(Name = "Descripción")]
        public string? DailyCheckDescription { get; set; }

        /*
         * Internal identifier of the Income Concentrate record
         * used by the Daily Check.
         *
         * The user does not select this value manually. The Service
         * obtains the latest active Income Concentrate of the Brood.
         */
        public int IncomeConcentrateId { get; set; }

        /*
         * Information obtained from the selected Brood and its
         * latest active Income Concentrate record.
         *
         * These properties are displayed as read-only values and
         * are not trusted when saving the Daily Check.
         */
        [Display(Name = "Cantidad inicial de aves")]
        public int BroodBirdInitialNum { get; set; }

        [Display(Name = "Concentrado acumulado (kg)")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal IncomeAccumulated { get; set; }

        /*
         * Calculated values may be displayed as read-only fields
         * but are always recalculated by the Service before saving.
         */
        [Display(Name = "Mortalidad diaria total")]
        public int TotalDailyMortality { get; set; }

        [Display(Name = "Mortalidad acumulada")]
        public int AccumulatedMortality { get; set; }

        [Display(Name = "Saldo de aves")]
        public int DailyBirdBalance { get; set; }

        [Display(Name = "Consumo en kilos")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal ConsumptionKilos { get; set; }

        [Display(Name = "Consumo acumulado (kg)")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal AccumulatedConsumption { get; set; }

        [Display(Name = "Saldo de concentrado (kg)")]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public decimal ConcentrateBalance { get; set; }

        /*
         * Dropdown options loaded by the Service layer.
         */
        public IEnumerable<SelectListItem> BroilerHouseOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> BroodOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> DailyCheckDayOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> DailyCheckWeekOptions { get; set; }
            = new List<SelectListItem>();
    }
}