using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ProjectGranjaLaFlor.Models.ViewModels
{
    /*
     * Represents the Daily Check filters, dropdown options
     * and records required by the Index view.
     */
    public class DailyCheckFilterViewModel
    {
        [Display(Name = "Camada")]
        public string? BroodName { get; set; }

        [Display(Name = "Año")]
        public int? Year { get; set; }

        [Display(Name = "Pollera")]
        public int? BroilerHouseId { get; set; }

        [Display(Name = "Semana de control")]
        public string? DailyCheckWeek { get; set; }

        [Display(Name = "Día de control")]
        public string? DailyCheckDay { get; set; }

        /*
         * Dropdown options generated by the Service layer.
         */
        public IEnumerable<SelectListItem> BroodOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> YearOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> BroilerHouseOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> DailyCheckWeekOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> DailyCheckDayOptions { get; set; }
            = new List<SelectListItem>();

        /*
         * Daily Check records matching the selected filters.
         */
        public IEnumerable<DailyCheckListViewModel> DailyChecks { get; set; }
            = new List<DailyCheckListViewModel>();
    }
}