using DB_GranjaLaFlor.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectGranjaLaFlor.Models.ViewModels;

/*
    *NOTE: SoftDeleteAsync is "imcomplete" since we are not implementing inactive and activate functions as it may break busniess logic and it is not really required. 
*/


namespace DB_GranjaLaFlor.Controllers
{
    /*
     * Architecture Decision | Thin Controller
     * Controllers coordinate HTTP requests and responses only.
     * Business rules, calculations and database operations are delegated
     * to the Service layer.
     */
    [Authorize]
    public class DailyChecksController : Controller
    {
        private readonly DailyCheckService _dailyCheckService;
        private readonly ILogger<DailyChecksController> _logger;

        public DailyChecksController(
            DailyCheckService dailyCheckService,
            ILogger<DailyChecksController> logger)
        {
            _dailyCheckService = dailyCheckService;
            _logger = logger;
        }

        /*
         * UI Request | Daily Check Index
         * Receives the optional filters selected by the user and delegates
         * the retrieval of records and dropdown options to the Service layer.
         */
        [HttpGet]
        public async Task<IActionResult> Index(
            int? broodId,
            int? year,
            int? broilerHouseId,
            string? dailyCheckWeek,
            string? dailyCheckDay)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.Index(). " +
                "BroodId: {BroodId}, " +
                "Year: {Year}, " +
                "BroilerHouseId: {BroilerHouseId}, " +
                "DailyCheckWeek: {DailyCheckWeek}, " +
                "DailyCheckDay: {DailyCheckDay}",
                broodId,
                year,
                broilerHouseId,
                dailyCheckWeek,
                dailyCheckDay);

            /*
             * Delegates the Daily Check records, current filter values
             * and dropdown menu options to the Service layer.
             */
            var model = await _dailyCheckService.GetFilterViewModelAsync(
                broodId,
                year,
                broilerHouseId,
                dailyCheckWeek,
                dailyCheckDay);

            return View(model);
        }

        /*
         * GET: DailyChecks/Create
         * Displays the Create view and loads the information
         * required to register a new Daily Check.
         */
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            _logger.LogInformation(
                "Entering DailyChecksController.Create() GET.");

            var model =
                await _dailyCheckService.GetCreateViewModelAsync();

            return View(model);
        }

        /*
 * POST: DailyChecks/Create
 *
 * Receives the Daily Check information entered by the user
 * and delegates business validation, calculations and
 * persistence to the Service layer.
 */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            DailyCheckFormViewModel model)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.Create() POST. " +
                "BroilerHouseId: {BroilerHouseId}, " +
                "BroodId: {BroodId}, " +
                "DailyCheckDate: {DailyCheckDate}, " +
                "DailyCheckWeek: {DailyCheckWeek}, " +
                "DailyCheckDay: {DailyCheckDay}",
                model.BroilerHouseId,
                model.BroodId,
                model.DailyCheckDate,
                model.DailyCheckWeek,
                model.DailyCheckDay);

            /*
             * Request Validation | ViewModel
             *
             * If Data Annotation validation fails, the form options
             * must be loaded again before returning the Create view.
             */
            if (!ModelState.IsValid)
            {
                await _dailyCheckService
                    .PopulateFormOptionsAsync(model);

                return View(model);
            }

            try
            {
                /*
                 * Business Operation | Create Daily Check
                 *
                 * Business rules, calculations and database persistence
                 * are handled by DailyCheckService.
                 */
                await _dailyCheckService.CreateAsync(model);

                TempData["SuccessMessage"] =
                    "El control diario fue registrado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                /*
                 * Business Validation Error
                 *
                 * Displays the validation generated by the Service
                 * inside the Create form.
                 */
                _logger.LogWarning(
                    ex,
                    "Business rule validation failed while creating Daily Check. " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}, " +
                    "DailyCheckDate: {DailyCheckDate}, " +
                    "DailyCheckWeek: {DailyCheckWeek}, " +
                    "DailyCheckDay: {DailyCheckDay}",
                    model.BroilerHouseId,
                    model.BroodId,
                    model.DailyCheckDate,
                    model.DailyCheckWeek,
                    model.DailyCheckDay);

                ModelState.AddModelError(
                    string.Empty,
                    ex.Message);

                await _dailyCheckService
                    .PopulateFormOptionsAsync(model);

                return View(model);
            }
            catch (Exception ex)
            {
                /*
                 * Unexpected Application Error
                 */
                _logger.LogError(
                    ex,
                    "Unexpected error while creating Daily Check. " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}, " +
                    "DailyCheckDate: {DailyCheckDate}",
                    model.BroilerHouseId,
                    model.BroodId,
                    model.DailyCheckDate);

                ModelState.AddModelError(
                    string.Empty,
                    "No se pudo registrar el control diario. " +
                    "Intente nuevamente.");

                await _dailyCheckService
                    .PopulateFormOptionsAsync(model);

                return View(model);
            }
        }

        /*
         * UI Request | Broods by Broiler House
         * Retrieves the active Broods associated with the selected
         * Broiler House and returns them to the Create or Edit view.
         */
        [HttpGet]
        public async Task<IActionResult> GetBroodsByBroilerHouse(
            int broilerHouseId)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.GetBroodsByBroilerHouse(). " +
                "BroilerHouseId: {BroilerHouseId}",
                broilerHouseId);

            if (broilerHouseId <= 0)
            {
                _logger.LogWarning(
                    "Invalid BroilerHouseId received while retrieving Broods. " +
                    "BroilerHouseId: {BroilerHouseId}",
                    broilerHouseId);

                return BadRequest(new
                {
                    message =
                        "Debe seleccionar una pollera válida."
                });
            }

            var broodOptions =
                await _dailyCheckService
                    .GetBroodsByBroilerHouseAsync(
                        broilerHouseId);

            return Json(broodOptions.Select(option => new
            {
                value = option.Value,
                text = option.Text
            }));
        }

        /*
         * UI Request | Selected Brood Information
         *
         * Retrieves the Brood, mortality and concentrate information
         * displayed after selecting a Broiler House, Brood and
         * Daily Check date.
         *
         * The Daily Check date is required because the Service must
         * determine which Income Concentrate was actually available
         * on or before that operational date.
         */
        [HttpGet]
        public async Task<IActionResult> GetBroodInformation(
            int broilerHouseId,
            int broodId,
            DateTime? dailyCheckDate)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.GetBroodInformation(). " +
                "BroilerHouseId: {BroilerHouseId}, " +
                "BroodId: {BroodId}, " +
                "DailyCheckDate: {DailyCheckDate}",
                broilerHouseId,
                broodId,
                dailyCheckDate);


            /*
             * Request Validation | Identifiers
             *
             * Confirms that a valid Broiler House and Brood
             * were received from the Daily Check form.
             */
            if (broilerHouseId <= 0 ||
                broodId <= 0)
            {
                _logger.LogWarning(
                    "Invalid identifiers received while retrieving " +
                    "Daily Check Brood information. " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}",
                    broilerHouseId,
                    broodId);

                return BadRequest(new
                {
                    message =
                        "Debe seleccionar una pollera y una camada válidas."
                });
            }


            /*
             * Request Validation | Daily Check Date
             *
             * The date is required to determine the most recent
             * Income Concentrate available at the time of the
             * Daily Check.
             */
            if (!dailyCheckDate.HasValue)
            {
                _logger.LogWarning(
                    "Daily Check date was not provided while retrieving " +
                    "Brood information. " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}",
                    broilerHouseId,
                    broodId);

                return BadRequest(new
                {
                    message =
                        "Debe seleccionar una fecha válida para el control diario."
                });
            }


            /*
             * UI Data | Brood Information
             *
             * Delegates the retrieval and calculation of the
             * current Brood information to DailyCheckService.
             */
            var broodInformation =
                await _dailyCheckService
                    .GetBroodInformationAsync(
                        broilerHouseId,
                        broodId,
                        dailyCheckDate.Value);


            /*
             * Business Validation | Available Brood Information
             */
            if (broodInformation == null)
            {
                _logger.LogWarning(
                    "Daily Check Brood information was not found. " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}, " +
                    "DailyCheckDate: {DailyCheckDate}",
                    broilerHouseId,
                    broodId,
                    dailyCheckDate.Value);

                return NotFound(new
                {
                    message =
                        "La camada seleccionada no está disponible " +
                        "o no existe un ingreso de concentrado disponible " +
                        "para la fecha seleccionada."
                });
            }


            /*
             * JSON Response | Daily Check Form
             *
             * Returns the operational values required by the
             * Create or Edit form.
             */
            return Json(new
            {
                broodInformation.BroilerHouseId,
                broodInformation.BroodId,
                broodInformation.BroodBirdInitialNum,
                broodInformation.IncomeConcentrateId,
                broodInformation.IncomeAccumulated,
                broodInformation.AccumulatedMortality,
                broodInformation.DailyBirdBalance,
                broodInformation.AccumulatedConsumption,
                broodInformation.ConcentrateBalance
            });
        }

        /*
         * GET: DailyChecks/Details/5
         * Retrieves and displays the complete information
         * of the selected Daily Check.
         */
        [HttpGet]
        public async Task<IActionResult> Details(
            int? id)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.Details(). " +
                "DailyCheckId: {DailyCheckId}",
                id);

            if (!id.HasValue)
            {
                _logger.LogWarning(
                    "Daily Check Details request received without an identifier.");

                TempData["ErrorMessage"] =
                    "No se proporcionó un identificador válido para consultar el control diario.";

                return RedirectToAction(nameof(Index));
            }

            try
            {
                var dailyCheck =
                    await _dailyCheckService.GetByIdAsync(
                        id.Value);

                if (dailyCheck == null)
                {
                    _logger.LogWarning(
                        "Daily Check was not found while loading Details. " +
                        "DailyCheckId: {DailyCheckId}",
                        id.Value);

                    TempData["ErrorMessage"] =
                        "El control diario seleccionado no existe.";

                    return RedirectToAction(nameof(Index));
                }

                return View(dailyCheck);
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Unexpected error while loading Daily Check Details. " +
                    "DailyCheckId: {DailyCheckId}",
                    id.Value);

                TempData["ErrorMessage"] =
                    "No se pudo consultar el detalle del control diario. " +
                    "Intente nuevamente.";

                return RedirectToAction(nameof(Index));
            }
        }


        /*
 * GET: DailyChecks/Delete/5
 * Retrieves and displays the Daily Check information
 * required to confirm its logical deactivation.
 */
        [HttpGet]
        public async Task<IActionResult> Delete(
            int? id)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.Delete() GET. " +
                "DailyCheckId: {DailyCheckId}",
                id);

            if (!id.HasValue)
            {
                _logger.LogWarning(
                    "Daily Check Delete request received without an identifier.");

                TempData["ErrorMessage"] =
                    "No se proporcionó un identificador válido para desactivar el control diario.";

                return RedirectToAction(nameof(Index));
            }

            try
            {
                var dailyCheck =
                    await _dailyCheckService.GetByIdAsync(
                        id.Value);

                if (dailyCheck == null)
                {
                    _logger.LogWarning(
                        "Daily Check was not found while loading Delete. " +
                        "DailyCheckId: {DailyCheckId}",
                        id.Value);

                    TempData["ErrorMessage"] =
                        "El control diario seleccionado no existe.";

                    return RedirectToAction(nameof(Index));
                }

                if (!dailyCheck.DailyCheckState)
                {
                    _logger.LogWarning(
                        "Inactive Daily Check received while loading Delete. " +
                        "DailyCheckId: {DailyCheckId}",
                        id.Value);

                    TempData["ErrorMessage"] =
                        "El control diario seleccionado ya se encuentra inactivo.";

                    return RedirectToAction(nameof(Index));
                }

                return View(dailyCheck);
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Unexpected error while loading Daily Check Delete. " +
                    "DailyCheckId: {DailyCheckId}",
                    id.Value);

                TempData["ErrorMessage"] =
                    "No se pudo cargar la información del control diario. " +
                    "Intente nuevamente.";

                return RedirectToAction(nameof(Index));
            }
        }

        /*
         * GET: DailyChecks/Edit: Retrieves and displays the active Daily Check information required to update the selected record.
         */
        [HttpGet]
        public async Task<IActionResult> Edit(
            int? id)
        {
            _logger.LogInformation("Entering DailyChecksController.Edit() GET. " + "DailyCheckId: {DailyCheckId}", id);

            if (!id.HasValue)
            {
                _logger.LogWarning( "Daily Check Edit request received without an identifier.");

                TempData["ErrorMessage"] = "No se proporcionó un identificador válido para editar el control diario.";

                return RedirectToAction(nameof(Index));
            }

            try
            {
                var model =
                    await _dailyCheckService.GetFormByIdAsync(
                        id.Value);

                if (model == null)
                {
                    _logger.LogWarning(
                        "Daily Check was not found or is inactive while loading Edit. " +
                        "DailyCheckId: {DailyCheckId}",
                        id.Value);

                    TempData["ErrorMessage"] =
                        "El control diario seleccionado no existe o se encuentra inactivo.";

                    return RedirectToAction(nameof(Index));
                }

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Unexpected error while loading Daily Check Edit. " +
                    "DailyCheckId: {DailyCheckId}",
                    id.Value);

                TempData["ErrorMessage"] =
                    "No se pudo cargar la información del control diario. " +
                    "Intente nuevamente.";

                return RedirectToAction(nameof(Index));
            }
        }

        /*
         * POST: DailyChecks/Edit: Receives the updated Daily Check information and delegates validation, persistence and recalculation to the Service layer.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            DailyCheckFormViewModel model)
        {
            _logger.LogInformation("Entering DailyChecksController.Edit() POST. " + "DailyCheckId: {DailyCheckId}, " + "BroilerHouseId: {BroilerHouseId}, " +
                "BroodId: {BroodId}, " + "DailyCheckWeek: {DailyCheckWeek}, " + "DailyCheckDay: {DailyCheckDay}",
                model.DailyCheckId, model.BroilerHouseId, model.BroodId, model.DailyCheckWeek, model.DailyCheckDay
                );

            if (!ModelState.IsValid)
            {
                await _dailyCheckService
                    .PopulateFormOptionsAsync(model);

                return View(model);
            }

            try
            {
                await _dailyCheckService.UpdateAsync(
                    model);

                TempData["SuccessMessage"] =
                    "El control diario fue actualizado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(
                    ex,
                    "Business rule validation failed while updating Daily Check. " +
                    "DailyCheckId: {DailyCheckId}, " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}, " +
                    "DailyCheckWeek: {DailyCheckWeek}, " +
                    "DailyCheckDay: {DailyCheckDay}",
                    model.DailyCheckId,
                    model.BroilerHouseId,
                    model.BroodId,
                    model.DailyCheckWeek,
                    model.DailyCheckDay);

                ModelState.AddModelError(
                    string.Empty,
                    ex.Message);

                await _dailyCheckService
                    .PopulateFormOptionsAsync(model);

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Unexpected error while updating Daily Check. " +
                    "DailyCheckId: {DailyCheckId}, " +
                    "BroilerHouseId: {BroilerHouseId}, " +
                    "BroodId: {BroodId}, " +
                    "DailyCheckWeek: {DailyCheckWeek}, " +
                    "DailyCheckDay: {DailyCheckDay}",
                    model.DailyCheckId,
                    model.BroilerHouseId,
                    model.BroodId,
                    model.DailyCheckWeek,
                    model.DailyCheckDay);

                TempData["ErrorMessage"] =
                    "No se pudo actualizar el control diario. " +
                    "Intente nuevamente.";

                await _dailyCheckService
                    .PopulateFormOptionsAsync(model);

                return View(model);
            }
        }

        /*
         * POST: DailyChecks/Delete/5
         * Delegates the logical deactivation of the selected Daily Check
         * and the recalculation of the remaining active records to the Service.
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(
            int id)
        {
            _logger.LogInformation(
                "Entering DailyChecksController.Delete() POST. " +
                "DailyCheckId: {DailyCheckId}",
                id);

            try
            {
                await _dailyCheckService.SoftDeleteAsync(
                    id);

                TempData["SuccessMessage"] =
                    "El control diario fue desactivado correctamente.";

                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(
                    ex,
                    "Business rule validation failed while deactivating " +
                    "Daily Check. DailyCheckId: {DailyCheckId}",
                    id);

                TempData["ErrorMessage"] =
                    ex.Message;

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Unexpected error while deactivating Daily Check. " +
                    "DailyCheckId: {DailyCheckId}",
                    id);

                TempData["ErrorMessage"] =
                    "No se pudo desactivar el control diario. " +
                    "Intente nuevamente.";

                return RedirectToAction(nameof(Index));
            }
        }


    }
}