using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ProjectGranjaLaFlor.Models.ViewModels.WeeklyCheck
{
    /*
     * Represents the Weekly Check filters, dropdown options
     * and records required by the Index view.
     */
    public class WeeklyCheckFilterViewModel
    {
        [Display(Name = "Pollera")]
        public int? BroilerHouseId { get; set; }

        [Display(Name = "Camada")]
        public int? BroodId { get; set; }

        [Display(Name = "Año")]
        public int? Year { get; set; }

        [Display(Name = "Semana")]
        public string? WeeklyCheckWeek { get; set; }

        /*
         * Dropdown options generated by the Service layer.
         */
        public IEnumerable<SelectListItem> BroilerHouseOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> BroodOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> YearOptions { get; set; }
            = new List<SelectListItem>();

        public IEnumerable<SelectListItem> WeeklyCheckWeekOptions { get; set; }
            = new List<SelectListItem>();

        /*
         * Weekly Check records matching the selected filters.
         */
        public IEnumerable<WeeklyCheckListViewModel> WeeklyChecks { get; set; }
            = new List<WeeklyCheckListViewModel>();
    }
}